program		= expression ;
expression	= definition ;

(* Expressions *)
definition	= ('var' | modifier {modifier}) index ['=' expression]
			| ('var' | modifier {modifier}) index fn
			| index ':=' expression
			| assignment ;
assignment	= index '=' expression
			| function ;
function	= fn | comparison ;
comparison	= bitwise {('==' | '!=' | '<' | '>' | '<=' | '>=') bitwise} ;
bitwise		= addsub {('>>' | '<<') addsub} ;
addsub		= muldiv {('+' | '-') muldiv} ;
muldiv		= unary {('*' | '/') unary} ;
unary		= ('-' | '!' | '...') unary
			| call ;
call		= index index {index} ;
index		= [primary] {'.' (Identifier | '[' expression ']')} ;
primary		= Identifier | Number | String | group | list | block ;
list		= '[' explist ']' ;
group		= '(' explist ')' ;

(* Blocks and statements *)
block		= '{' {statement | ';'} '}';
statement	= 'return' expression
			| 'yield' expression
			| 'if' expression ':' statement ['else' statement]
			| 'while' expression ':' statement
			| expression ;

(* Smaller components *)
fn			= (Identifier | '(' paramlist ')') '=>' expression ;
explist		= expression {',' expression} ;
paramlist	= param {',' param} ;
param		= expression ;
modifier	= 'const' | 'instance' ;
