program		= expression ;
expression	= assignment ;

(* Expressions *)
assignment	= index {'=' expression | ':=' expression}
			| function ;
function	= (Identifier | '(' paramlist ')') '=>' expression
			| comparison ;
comparison	= bitwise {('==' | '!=' | '<' | '>' | '<=' | '>=') bitwise} ;
bitwise		= addsub {('>>' | '<<') addsub} ;
addsub		= muldiv {('+' | '-') muldiv} ;
muldiv		= unary {('*' | '/') unary} ;
unary		= ('-' | '!' | '...') unary
			| call ;
call		= index index {index} ;
index		= [primary] {'.' (Identifier | '[' expression ']')} ;
primary		= Identifier | Number | String | group | list | block ;
list		= '[' explist ']' ;
group		= '(' explist ')' ;

(* Blocks and statements *)
block		= '{' {statement | ';'} '}';
statement	= 'return' expression
			| 'yield' expression
			| 'if' expression ':' statement ['else' statement]
			| 'while' expression ':' statement
			| expression ;

(* Smaller components *)
explist		= expression {',' expression} ;
paramlist	= param {',' param} ;
param		= expression
